try:
  print(x)
except:
  print("무언가 잘못됐습니다.")
finally:
  print("'try except'가 끝났습니다.") 

